[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_lend_borrow = 'FuWX5XFcPGoJ5daJhMhxLFuKDZSXK8Tvqo4vGqhW9mGj'

[programs.devnet]
nft_lend_borrow = 'FuWX5XFcPGoJ5daJhMhxLFuKDZSXK8Tvqo4vGqhW9mGj'

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
